#Updated via API
#Thu May 07 10:07:18 EDT 2026
server.error.include-message=always
server.port=8081
spring.application.name=crs-reivew-api
spring.jackson.serialization.indent-output=true
veracode.api.ai-engines=Google Gemini,Azure OpenAI,OpenAI,Anthropic
veracode.api.architecture-mappings.Go=go,golang,GO,GOLANG
veracode.api.architecture-mappings.Java=maven,gradle,JAVA,JVM
veracode.api.architecture-mappings.JavaScript=npm,bower,JAVASCRIPT
veracode.api.architecture-mappings.NET=nuget,CIL32,MSIL
veracode.api.architecture-mappings.PHP=composer,PHP
veracode.api.architecture-mappings.Python=pip,pypi,PYTHON
veracode.api.architecture-mappings.Ruby=rubygems,RUBY
veracode.api.azureDeployment=gpt-4o
veracode.api.azureEndpoint=https\://mazi7-mmobcd43-eastus2.openai.azure.com
veracode.api.azureKey=
veracode.api.debug=true
veracode.api.geminiKey=
veracode.api.geminiModel=gemini-2.5-flash
veracode.api.grace-periods.tier-1.High=10
veracode.api.grace-periods.tier-1.Low=180
veracode.api.grace-periods.tier-1.Medium=30
veracode.api.grace-periods.tier-1.VeryHigh=10
veracode.api.grace-periods.tier-2.High=10
veracode.api.grace-periods.tier-2.Low=180
veracode.api.grace-periods.tier-2.Medium=30
veracode.api.grace-periods.tier-2.VeryHigh=10
veracode.api.grace-periods.tier-3a.High=30
veracode.api.grace-periods.tier-3a.Low=180
veracode.api.grace-periods.tier-3a.Medium=60
veracode.api.grace-periods.tier-3a.VeryHigh=30
veracode.api.grace-periods.tier-3b.High=60
veracode.api.grace-periods.tier-3b.Low=180
veracode.api.grace-periods.tier-3b.Medium=90
veracode.api.grace-periods.tier-3b.VeryHigh=60
veracode.api.grace-periods.tier-4.High=60
veracode.api.grace-periods.tier-4.Low=180
veracode.api.grace-periods.tier-4.Medium=90
veracode.api.grace-periods.tier-4.VeryHigh=60
veracode.api.history-limit=10
veracode.api.ignore-ecosystems=so
veracode.api.ignore-modules=Microsoft,Azure,System,AspNetCore,Newtonsoft,EntityFramework,NLog,Log4Net,AutoMapper,AppInsights,UnitTesting,BouncyCastle,Serilog,Dapper,OpenXml,Serialization,OpenXmlPowerTools,GemBox,SharpDocx,Quartz,sni.dll,VeracodeJavaAPI.jar,.Tests.dll,.map,_nodemodule_
veracode.api.include-modules=veracodegen.htmla.pya,pwc.,.zip,.war,snapshot.jar,0.jar,pwc,release.jar,app_,.bca,.gz,-service.jar,-advancer.jar
veracode.api.sastPrompt=Expertly1 bashir analyze the following security mitigation customer comment and provide a concise, professional assessment or recommendation for a security auditor.
veracode.api.save-json-history=true
veracode.api.save-xml-logs=true
veracode.api.scaPrompt=Expertly1 analyze the following software composition analysis (SCA) finding. Provide a recommendation for the security auditor regarding the identified dependency risk.
veracode.api.tier-mappings.External.Confidential=tier-1
veracode.api.tier-mappings.External.HighlyConfidential=tier-1
veracode.api.tier-mappings.External.Internal=tier-2
veracode.api.tier-mappings.External.Public=tier-2
veracode.api.tier-mappings.Internal.Confidential=tier-3b
veracode.api.tier-mappings.Internal.HighlyConfidential=tier-3a
veracode.api.tier-mappings.Internal.Internal=tier-3b
veracode.api.tier-mappings.Internal.Public=tier-3b
veracode.api.url=https\://api.veracode.com
