spring.application.name=crs-reivew-api
server.port=8081
server.error.include-message=always
veracode.api.url=https://api.veracode.com
veracode.api.debug=true
spring.jackson.serialization.indent-output=true
veracode.api.ignore-modules=Microsoft,Azure,System,AspNetCore,Newtonsoft,EntityFramework,NLog,Log4Net,AutoMapper,AppInsights,UnitTesting,BouncyCastle,Serilog,Dapper,OpenXml,Serialization,OpenXmlPowerTools,GemBox,SharpDocx,Quartz,sni.dll,VeracodeJavaAPI.jar,.Tests.dll,.map,_nodemodule_
veracode.api.include-modules =veracodegen.htmla.pya,pwc.,.zip,.war,snapshot.jar,0.jar,pwc,release.jar,app_web,.bca,.gz,-service.jar,-advancer.jar
veracode.api.ignore-ecosystems=so

veracode.api.architecture-mappings..NET=nuget,CIL32,MSIL
veracode.api.architecture-mappings.JavaScript=npm,bower,JAVASCRIPT
veracode.api.architecture-mappings.Python=pip,pypi,PYTHON
veracode.api.architecture-mappings.Java=maven,gradle,JAVA,JVM
veracode.api.architecture-mappings.PHP=composer,PHP
veracode.api.architecture-mappings.Ruby=rubygems,RUBY
veracode.api.architecture-mappings.Go=go,golang,GO,GOLANG