spring.application.name=crs-reivew-api
server.port=8081
server.error.include-message=always
veracode.api.url=https://api.veracode.com
veracode.api.debug=true
spring.jackson.serialization.indent-output=true
veracode.api.ignore-modules=Microsoft,Azure,System,AspNetCore,Newtonsoft,EntityFramework,NLog,Log4Net,AutoMapper,AppInsights,UnitTesting,BouncyCastle,Serilog,Dapper,OpenXml,Serialization,OpenXmlPowerTools,GemBox,SharpDocx,Quartz,sni.dll,VeracodeJavaAPI.jar,.Tests.dll
veracode.api.include-modules =veracodegen.htmla.pya,pwc.,.zip,.war,snapshot.jar,0.jar,pwc,release.jar,app_web,.bca,.gz,-service.jar,-advancer.jar